version: '3.8'

services:
  video-review-app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if using HTTPS
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.video-review.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.video-review.tls=true"
      - "traefik.http.routers.video-review.tls.certresolver=letsencrypt"

  # Optional: Traefik for reverse proxy and SSL
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

